name: Ubuntu x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install Downloader Dependencies
      run: dotnet restore ./src/Downloader/Downloader.csproj
    - name: Build Downloader Project
      run: dotnet build ./src/Downloader/Downloader.csproj
    - name: Push nuget package
      run: |
        # Grab some versioning information
        commithash=$(git rev-parse --short HEAD)
        currtime=$(date +%s)
        echo "commit hash is $commithash"
        echo "time is $currtime"

        # Enter project directory
        cd src/Downloader

        # Build package
        dotnet restore
        dotnet build

        # Pack a nuget package with all the default config
        dotnet pack

        # Enter package output directory
        cd bin/Debug

        # Getting file named with .nupkg extension
        file=""
        cdir=`ls ./*.nupkg`
        echo $cdir
        for eachfile in $cdir
        do
          file=$eachfile
        done

        echo $file
        
        # Push it to source "nuget"
        dotnet nuget add source --username SinoAHpx --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SinoAHpx/index.json"
        dotnet nuget push $file --api-key ${{ secrets.PAT  }} --source "github" --skip-duplicate